version: "3.7"

volumes:
  caddy_data:
  caddy_config:
  shiny_apps:
  postgis_data:

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /share:/share

  rstudio:
    container_name: rstudio
    build: ./rstudio-shiny
    environment:
      ROOT: 'true'
      USER: admin
      PASSWORD: $PASSWORD
      ADD: shiny
    ports:
      - 8787:8787  # rstudio
      - 3838:3838  # shiny
      - 8888:8888  # api
    restart: unless-stopped
    volumes:
      - /share:/share
      - shiny_apps:/srv/shiny-server

  postgis:
    container_name: postgis
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: msens
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $PASSWORD
    volumes:
      - postgis_data:/var/lib/postgresql
      - ./postgis/postgresql.conf:/etc/postgresql/postgresql.conf
      - /share:/share
    restart: unless-stopped
    healthcheck:
      test: 'exit 0'
    ports:
      - 5432:5432

  # tile:
  #   container_name: tile
  #   environment:
  #     DATABASE_URL: postgres://admin:$PASSWORD@postgis:5432/msens
  #   image: pramsey/pg_tileserv:latest
  #   depends_on:
  #     - postgis
  #   ports:
  #     - 7800:7800

  # rest:
  #   container_name: rest
  #   environment:
  #     PGRST_DB_URI: postgres://ro_user:$ROPASS@postgis:5432/msens
  #     PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
  #     PGRST_DB_ANON_ROLE: ro_user  # db-anon-role
  #   image: postgrest/postgrest
  #   depends_on:
  #     - postgis
  #   ports:
  #     - "3000:3000"
